name: cunning_document_scanner
description: 一个用于 Flutter 的文档扫描插件。在 iOS 和 Android 上自动扫描和裁剪文档。
version: 1.3.1
homepage: https://cunning.biz
repository: https://github.com/jachzen/cunning_document_scanner

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0+1
  permission_handler_platform_interface: ^4.3.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <7.0.0"
  mockito: ^5.4.5

# 有关此文件的通用 Dart 部分的信息，请参见以下页面：
# https://dart.dev/tools/pub/pubspec

# 以下部分特定于 Flutter。
flutter:
  # 此部分将此 Flutter 项目标识为插件项目。
  # 通常不应修改 'pluginClass' 和 Android 'package' 标识符。
  # 工具使用它们在为此项目添加或更新资源时保持一致性。
  plugin:
    platforms:
      android:
        package: biz.cunning.cunning_document_scanner
        pluginClass: CunningDocumentScannerPlugin
      ios:
        pluginClass: CunningDocumentScannerPlugin
